export const ACCOUNT_ICON_FALLBACK = "wallet" as const;

export const ACCOUNT_ICON_NAMES = [
  "wallet",
  "landmark",
  "credit-card",
  "piggy-bank",
  "building",
  "smartphone",
  "banknote",
  "receipt",
  "briefcase",
  "home",
  "car",
  "plane",
  "coffee",
  "shopping-bag",
  "sparkles",
  "wrench",
  "trending-up",
  "trending-down",
  "circle-dollar-sign",
  "badge-euro",
  "badge-dollar-sign",
  "hand-coins",
  "handshake",
  "shield",
  "lock",
  "key",
  "chart-pie",
  "chart-bar",
  "chart-line",
  "percent",
  "coins",
  "vault",
  "gift",
  "heart",
  "tag",
  "file-text",
  "calendar",
  "store",
  "shopping-cart",
  "cable",
  "wifi",
  "zap",
  "droplets",
  "train",
  "bus",
  "bike",
  "fuel",
] as const;

export type AccountIconName = (typeof ACCOUNT_ICON_NAMES)[number];

export const KNOWN_ACCOUNT_ICONS = [
  ...ACCOUNT_ICON_NAMES,
  ACCOUNT_ICON_FALLBACK,
] as const;
