export const CATEGORY_ICON_FALLBACK = "circle" as const;

export const CATEGORY_ICON_NAMES = [
  "shopping-cart",
  "banknote",
  "home",
  "car",
  "utensils",
  "heart",
  "gamepad-2",
  "briefcase",
  "gift",
  "plane",
  "credit-card",
  "wallet",
  "piggy-bank",
  "receipt",
  "trending-up",
  "trending-down",
  "coffee",
  "smartphone",
  "laptop",
  "wifi",
  "zap",
  "droplets",
  "fuel",
  "bus",
  "train",
  "bike",
  "dumbbell",
  "pill",
  "baby",
  "dog",
  "shopping-bag",
  "shirt",
  "book",
  "graduation-cap",
  "music",
  "building",
  "wrench",
  "sparkles",
  "tree-pine",
  "pizza",
  "beer",
  "landmark",
  "stethoscope",
] as const;

export type CategoryIconName = (typeof CATEGORY_ICON_NAMES)[number];

export const KNOWN_CATEGORY_ICONS = [
  ...CATEGORY_ICON_NAMES,
  CATEGORY_ICON_FALLBACK,
] as const;
