import {
  Baby,
  Banknote,
  Beer,
  Bike,
  Book,
  Briefcase,
  Building,
  Bus,
  Car,
  Circle,
  Coffee,
  CreditCard,
  Dog,
  Droplets,
  Dumbbell,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  Home,
  Landmark,
  Laptop,
  Music,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Receipt,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Train,
  TreePine,
  TrendingDown,
  TrendingUp,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { CATEGORY_ICON_FALLBACK } from "@/lib/constants/category-icons";

const ICON_MAP: Record<string, LucideIcon> = {
  "shopping-cart": ShoppingCart,
  banknote: Banknote,
  home: Home,
  car: Car,
  utensils: Utensils,
  heart: Heart,
  "gamepad-2": Gamepad2,
  briefcase: Briefcase,
  gift: Gift,
  plane: Plane,
  "credit-card": CreditCard,
  wallet: Wallet,
  "piggy-bank": PiggyBank,
  receipt: Receipt,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  coffee: Coffee,
  smartphone: Smartphone,
  laptop: Laptop,
  wifi: Wifi,
  zap: Zap,
  droplets: Droplets,
  fuel: Fuel,
  bus: Bus,
  train: Train,
  bike: Bike,
  dumbbell: Dumbbell,
  pill: Pill,
  baby: Baby,
  dog: Dog,
  "shopping-bag": ShoppingBag,
  shirt: Shirt,
  book: Book,
  "graduation-cap": GraduationCap,
  music: Music,
  building: Building,
  wrench: Wrench,
  sparkles: Sparkles,
  "tree-pine": TreePine,
  pizza: Pizza,
  beer: Beer,
  landmark: Landmark,
  stethoscope: Stethoscope,
  [CATEGORY_ICON_FALLBACK]: Circle,
};

type CategoryIconProps = {
  name: string;
  color: string;
  className?: string;
};

export function CategoryIcon({ name, color, className = "size-5" }: CategoryIconProps) {
  const Icon = ICON_MAP[name] ?? Circle;
  return <Icon className={className} style={{ color }} />;
}
