import {
  Banknote,
  BadgeDollarSign,
  BadgeEuro,
  Bike,
  Briefcase,
  Building,
  Bus,
  Cable,
  Car,
  Calendar,
  ChartBar,
  ChartLine,
  ChartPie,
  CircleDollarSign,
  Coins,
  Coffee,
  CreditCard,
  Droplets,
  FileText,
  Fuel,
  Gift,
  HandCoins,
  Handshake,
  Heart,
  Home,
  Key,
  Landmark,
  Lock,
  Percent,
  PiggyBank,
  Plane,
  Receipt,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Tag,
  Train,
  TrendingDown,
  TrendingUp,
  Vault,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  wallet: Wallet,
  landmark: Landmark,
  "credit-card": CreditCard,
  "piggy-bank": PiggyBank,
  building: Building,
  smartphone: Smartphone,
  banknote: Banknote,
  receipt: Receipt,
  briefcase: Briefcase,
  home: Home,
  car: Car,
  plane: Plane,
  coffee: Coffee,
  "shopping-bag": ShoppingBag,
  sparkles: Sparkles,
  wrench: Wrench,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "circle-dollar-sign": CircleDollarSign,
  "badge-euro": BadgeEuro,
  "badge-dollar-sign": BadgeDollarSign,
  "hand-coins": HandCoins,
  handshake: Handshake,
  shield: Shield,
  lock: Lock,
  key: Key,
  "chart-pie": ChartPie,
  "chart-bar": ChartBar,
  "chart-line": ChartLine,
  percent: Percent,
  coins: Coins,
  vault: Vault,
  gift: Gift,
  heart: Heart,
  tag: Tag,
  "file-text": FileText,
  calendar: Calendar,
  store: Store,
  "shopping-cart": ShoppingCart,
  cable: Cable,
  wifi: Wifi,
  zap: Zap,
  droplets: Droplets,
  train: Train,
  bus: Bus,
  bike: Bike,
  fuel: Fuel,
};

type AccountIconProps = {
  name: string;
  className?: string;
};

export function AccountIcon({ name, className = "size-5" }: AccountIconProps) {
  const Icon = ICON_MAP[name] ?? Wallet;
  return <Icon className={className} />;
}
